// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvgeySA7iovwsk8eaG7YtTzmQhLITHd-E',
    appId: '1:152986151993:web:e5a1eca49531e4f2b8f1e8',
    messagingSenderId: '152986151993',
    projectId: 'navgatiai-ca3ee',
    authDomain: 'navgatiai-ca3ee.firebaseapp.com',
    storageBucket: 'navgatiai-ca3ee.firebasestorage.app',
    measurementId: 'G-NZV1VZL3DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc5Z_xJQt8aoxsxuJS5SYPQBgDNiis5fI',
    appId: '1:152986151993:android:2dae95ff7332748db8f1e8',
    messagingSenderId: '152986151993',
    projectId: 'navgatiai-ca3ee',
    storageBucket: 'navgatiai-ca3ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7gTVycLPuyGzPunPI9h9_B4PAhO_q7M0',
    appId: '1:152986151993:ios:8579d7b08a86f8e4b8f1e8',
    messagingSenderId: '152986151993',
    projectId: 'navgatiai-ca3ee',
    storageBucket: 'navgatiai-ca3ee.firebasestorage.app',
    iosBundleId: 'com.example.navgatiAiEnterpreneur',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gTVycLPuyGzPunPI9h9_B4PAhO_q7M0',
    appId: '1:152986151993:ios:8579d7b08a86f8e4b8f1e8',
    messagingSenderId: '152986151993',
    projectId: 'navgatiai-ca3ee',
    storageBucket: 'navgatiai-ca3ee.firebasestorage.app',
    iosBundleId: 'com.example.navgatiAiEnterpreneur',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvgeySA7iovwsk8eaG7YtTzmQhLITHd-E',
    appId: '1:152986151993:web:dfbd488e5dc54292b8f1e8',
    messagingSenderId: '152986151993',
    projectId: 'navgatiai-ca3ee',
    authDomain: 'navgatiai-ca3ee.firebaseapp.com',
    storageBucket: 'navgatiai-ca3ee.firebasestorage.app',
    measurementId: 'G-TH8RQHDQKX',
  );
}
